main: serversystem.main.ServerSystem
name: ServerSystem
version: 2.2
author: Der_Zauberer
api-version: 1.17

commands:
  admin:
    description: Open the admin menu
    usage: /<command>
    permission: serversystem.command.admin
  build:
    description: Allow the player to build in protected worlds
    usage: /<command> [<player>]
    permission: serversystem.command.build
  enderchest:
    description: Open the enderchest of a player
    usage: /<command> [<player>]
    permission: serversystem.command.enderchest
  inventory:
    description: Open the inventory of a player
    usage: /<command> [<player>]
    permission: serversystem.command.inventory
  lobby:
    description: Teleport player to lobby
    usage: /<command>
    permission: serversystem.command.lobby
  permission:
    description: Set the permissions of a player
    usage: /<command> [<player>] [<group>]
  setwarp:
    description: Set a warp location
    usage: /<command> [name] [<item>] [<global>] [permission]
    permission: serversystem.command.setwarp
  removewarp:
    description: Remove a warp location
    usage: /<command> [<warp>]
    permission: serversystem.command.setwarp
  vanish:
    description: Allow the player to vanish
    usage: /<command> [<player>]
    permission: serversystem.command.vanish
  warp:
    description: Teleport player to a location
    usage: /<command> [<warp>]
    permission: serversystem.command.warp
    aliases: [warps]
  world:
    description: Teleport player to an other world or edit an other world
    usage: /<command> [<word>] [<player>]
    permission: serversystem.command.world
  wtp:
    description: Teleoprt player to an other world
    usage: /<command> [<word>]
    permission: serversystem.command.world
  
permissions:
  serversystem.command.admin:
    description: Open the admin inventory
    default: op
  serversystem.command.build:
    description: Allow the player to build in protected worlds
    default: op
  serversystem.command.enderchest:
    desciption: Open the enderchest of a player
    default: op
  serversystem.command.inventory:
    desciption: Open the inventory of a player
    default: op
  serversystem.command.lobby:
    description: Teleport player to lobby
    default: true
  serversystem.command.permission:
    description: Set the permissions of a player
    default: false
  serversystem.command.setwarp:
    description: Set a warp location
    default: op
  serversystem.command.vanish:
    description: Allow the player to vanish
    default: op
  serversystem.command.warp:
    description: Teleport player to an other world
    default: true
  serversystem.command.world:
    description: Teleport player to an other world or edit an other world
    default: op
  serversystem.tools.adminstar:
    description: Open the admin inventory
    default: op
  serversystem.tools.commandblock:
    description: Allow to use commandblocks
    default: false
  serversystem.tools.signeddit:
    description: Allow to create executable signs
    default: op